### ISSUE TITLE
Project Review (Module 10)

### ISSUE THREAD

**Issue by A-Tro-24** [hayhem/HAYLEYHEMME-MADA-project#3]
Hi Hayley,

I really enjoyed reviewing your project! I can see that you have planned everything out well and that you have quite a strong foundational knowledge for writing code in R. My only suggestion is that the mapping.R script could use a README file so those who are reviewing your project/trying to reproduce it can understand what code you're using, why you're using it, etc. Otherwise, everything seems clear, especially your data exploration scripts. This is very quality work, and I would assign a 3/3 for the work you've done!

**Comment by kellyhatfield** [comment]
Hey Haley!  My score is 3. 

You have done nice work data processing and organizing. Also, I think your initial analyses, particularly the PCA are very interesting. Finally, your models seem to be appropriate. I like that you compared Poisson with negative binomial to see which fit better, as both may be appropriate. 

My suggestions would be to include a readme for reproducibility - direct me through the steps. I appreciated the readme in the processing subfolder to tell how to process. Having one for the overall project would be helpful for where to start, etc. 
Nice work.

**Comment by hayhem** [comment]
I greatly appreciate the feedback. I agree with all your suggestions, and I will correct these in my project repository. Thank you!
